type TTrinhTham = { id:number; ten: string; hinh: string; tacgia: string; gia: string; ghichu: string; }
type TVanHoc = { id:number; ten: string; hinh: string; tacgia: string; gia: string; ghichu: string; }
type TTamLy = { id:number; ten: string; hinh: string; tacgia: string; gia: string; ghichu: string; }
type TThieuNhi = { id:number; ten: string; hinh: string; tacgia: string; gia: string; ghichu: string; }
    const trinhtham_arr: TTrinhTham[]= [ 
        {id:1, ten: "Phía Sau Nghi Can X", tacgia: "Higashino Keigo", gia: "109.000", hinh: "images/phiasaunghicanxnew01-80ba1d6b-9ecf-4695-9dc2-9f7c3d832433.webp", ghichu: "“Việc nghĩ ra một bài toán vô cùng khó và việc giải bài toán đó, việc nào khó hơn?”. Khi nhấn chuông cửa nhà nghi can chính của một vụ án mới, điều tra viên Kusanagi không biết rằng anh sắp phải đương đầu với một thiên tài ẩn dật. Kusanagi càng không thể ngờ rằng, chỉ một câu nói vô thưởng vô phạt của anh đã kéo người bạn thân, Manabu Yukawa, một phó giáo sư vật lý tài năng, vào vụ án. Và điều làm sững sờ nhất, đó là vụ án kia chẳng qua cũng chỉ như một bài toán cấp ba đơn giản, tuy nhiên ấn số X khi được phơi bày ra lại không đem đến hạnh phúc cho bất cứ ai…"},
        {id:2, ten: "Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya", tacgia: "Higashino Keigo", gia: "105.000", hinh: "images/2306bd865b5fe8b295cd0b63b58a0fe2.jpg", ghichu: "Một đêm vội vã lẩn trốn sau phi vụ khoắng đồ nhà người, Atsuya, Shota và Kouhei đã rẽ vào lánh tạm trong một căn nhà hoang bên con dốc vắng người qua lại. Căn nhà có vẻ khi xưa là một tiệm tạp hóa với biển hiệu cũ kỹ bám đầy bồ hóng, khiến người ta khó lòng đọc được trên đó viết gì. Định bụng nghỉ tạm một đêm rồi sáng hôm sau chuồn sớm, cả ba không ngờ chờ đợi cả bọn sẽ là một đêm không ngủ, với bao điều kỳ bí bắt đầu từ một phong thư bất ngờ gửi đến…"},
        {id:3, ten: "Thanh Gươm Do Dự", tacgia: "Higashino Keigo", gia: "199.000", hinh: "images/thanhguomdodu01.webp", ghichu: "Thanh gươm công lý liệu có đang vung đúng hướng?Thi thể của Ema, cô con gái duy nhất của Nagamine, được phát hiện ở hạ lưu sông Arakawa. Trên đường từ đêm hội pháo hoa về nhà, cô bé bị một nhóm nam sinh vị thành niên bắt cóc, cưỡng hiếp đến chết rồi thả trôi sông. Thông qua một cuộc điện thoại bí ẩn, Nagamien biết được thủ phạm và quyết định trả thù cho con gái. Người cha đó đã bị cảnh sát và giới truyền thông truy đuổi. Công lý là gì? Ai sẽ phán xét thủ phạm? Dư luận vào cuộc, và vụ án đi đến một cái kết bất ngờ. Thanh gươm do dự là tiểu thuyết xuất sắc dám thử sức một chủ đề nặng nề và buồn, có thể làm rung động trái tim bất cứ người đọc sách nào."},
    ];
    const vanhoc_arr: TVanHoc[]= [ 
        { id:1, ten:"Nhà Giả Kim", tacgia: "Paulo Coelho", gia: "69.000", hinh: "images/nha-gia-kim-1044.jpg", ghichu: "Tất cả những trải nghiệm trong chuyến phiêu du theo đuổi vận mệnh của mình đã giúp Santiago thấu hiểu được ý nghĩa sâu xa nhất của hạnh phúc, hòa hợp với vũ trụ và con người."},
        { id:2, ten:"Không Gia Đình", tacgia: "Hector Malot", gia: "132.000", hinh: "images/khong-gia-dinh-bc.jpg", ghichu: "Kể về cậu bé mồ côi Remi, bị bán làm người hát rong và phải tự mình đi khắp nước Pháp. Trên hành trình đầy gian truân, Remi học được lòng dũng cảm, sự kiên nhẫn, và giá trị của tình yêu thương gia đình."},
        { id:3, ten:"Bố Già", tacgia: "Mario Puzo", gia: "110.000", hinh: "images/bo-gia.jpg", ghichu: "Bố Già của Mario Puzo kể về cuộc sống và sự nghiệp của Vito Corleone, một trùm mafia quyền lực, và sự kế thừa quyền lực của con trai ông, Michael Corleone. Tác phẩm khai thác sâu về tình gia đình, lòng trung thành, và cuộc chiến ngầm giữa các gia đình mafia trong thế giới tội phạm."},
   ];
    const tamly_arr:TTamLy[]= [ 
        { id:1, ten:"Đắc Nhân Tâm", tacgia: "Dale Carnegie", gia: "108.000", hinh: "images/dacnhantam86.jpg", ghichu: "Cuốn sách dạy về nghệ thuật giao tiếp, cách tạo dựng mối quan hệ và thu phục lòng người. Qua các nguyên tắc tâm lý, sách giúp cải thiện kỹ năng lãnh đạo, thuyết phục và thành công trong công việc lẫn cuộc sống."},
        { id:2, ten:"Sức Mạnh Của Thói Quen", tacgia: "Charles Duhigg", gia: "210.000", hinh: "images/z4105964911654-5e5a35259898ca70607286170319aa65.webp", ghichu: "Tác phẩm cung cấp các chiến lược để hiểu, thay đổi và xây dựng thói quen tích cực nhằm đạt được mục tiêu."},
        { id:3, ten:"Tâm Lý Học Tội Phạm", tacgia: "David Canter", gia: "145.000", hinh: "images/ph_c-h_a-ch_n-dung-k_-ph_m-t_i.webp", ghichu: "Tâm lý học tội phạm nghiên cứu hành vi, suy nghĩ và động cơ của tội phạm, nhằm hiểu rõ nguyên nhân và yếu tố dẫn đến hành vi phạm tội. Tác phẩm thường phân tích các loại tội phạm khác nhau, từ đó hỗ trợ điều tra và phòng ngừa tội phạm."}
       ];
   const thieunhi_arr:TThieuNhi[]= [
    { id:1, ten:"Alice Ở Xứ Sở Diệu Kỳ", tacgia: "Lewis Carroll", gia: "150.000", hinh: "images/alice_1_41b0c4b26551419abc5007b399063feb.jpg", ghichu: "Cuộc phiêu lưu kỳ lạ của cô bé Alice trong thế giới thần tiên."},
    { id:2, ten:"Hoàng Tử Bé", tacgia: "Antoine de Saint-Exupéry", gia: "60.000", hinh: "images/hoang-tu-be.jpg", ghichu: "Một tác phẩm triết lý nhẹ nhàng về cuộc sống và tình yêu qua góc nhìn của một hoàng tử nhỏ từ hành tinh khác."},
    { id:3, ten:"Harry Potter", tacgia: "J.K. Rowling", gia: "1.200.000", hinh: "images/combo0112072017_2.webp", ghichu: "Một loạt sách phiêu lưu kỳ ảo về một cậu bé phù thủy và cuộc chiến chống lại thế lực hắc ám."}   
];
export {TTrinhTham, TVanHoc, TTamLy, TThieuNhi}
export {trinhtham_arr, vanhoc_arr, tamly_arr, thieunhi_arr}